breakfast_drink = "Juice/Milk/Coffee"
breakfast = [("Biscuits & Gravy; Hashbrowns, Fruit;"),
             ("Omelettes, Bacon; Applesauce;"),
             ("Cereal Hot/Cold; Fruit, Toast;"),
             ("Cream Cheese/Bagels; Ham, Fruit, Muffin;"),
             ("Oatmeal; Fruit, Cinn. Roll;"),
             ("Grits; Fruit, Muffin;"),
             ("Cream of Wheat; Toast, Fruit;"),
             ("Egg/Sausage Sandwich; Hashbrowns, Fruit;"),
             ("Buttermilk Pankcakes and Sausage; Yogurt, Toast, Fruit;"),
             ("Waffles; Ham, Hashbrowns, Fruit;"),
             ("Fruit Salad; Yogurt, Granola;"),
             ("Veggie Omelette; Whole Wheat Toast, Fruit;"),
             ("Whole Grain Cereal; Banana Slices, Almond Milk;"),
             ("Quinoa Breakfast Bowl; Sliced Strawberries, Almonds;"),
             ("Avocado Toast; Poached Egg, Fresh Fruit;"),
             ("Scrambled Eggs with Spinach; Whole Wheat English Muffin, Apple Slices;"),
             ("Breakfast Burrito; Black Beans, Salsa, Fresh Fruit;"),
             ("Whole Wheat Pancakes; Blueberry Compote, Greek Yogurt;"),
             ("Oatmeal with Nuts and Seeds; Fresh Orange Juice;"),
             ("Peanut Butter & Banana Toast; Chia Seeds, Honey, Fruit Salad;"),
             ("Sweet Potato Hash; Sautéed Spinach, Poached Egg;"),
             ("Egg White Frittata; Spinach, Mushrooms, Whole Wheat Toast;"),
             ("Chorizo w/Eggs; Fruit,Toast;")]

lunch = [("Chicken Quesadillas; Bean Salad; Pie;"),
         ("Chicken Egg Rolls; Fried Rice; Tapioca Pudding;"),
         ("Subway Sandwiches; Chips; Fruit Salad;"),
         ("Fetuccini Alfredo Chicken; Salad, Carrots; Cookies;"),
         ("Beef Stragonoff; Green Beans, Coleslaw; Cake;"),
         ("Coconut Shrimp; Sweet Pot., Asparagus; Strawberry Shortcake;"),
         ("Chicken Nuggets; Cucumber salad; Potato Salad; Brownies;"),
         ("Beef/Cheese Raviolis; Caesar Salad; Garlic Bread; Banana Pudding;"),
         ("Fish Tacos; Coleslaw; Zucchini and Cheese Casserole; Pie;"),
         ("BBQ Shredded Pork; Potato Salad; Veggies; Brownies;"),
         ("Shepherd's beef pie; Salad, Biscuit, Brownies;"),
         ("Tomato Soup; Ham and Cheese Sandwiches; Root-Beer Floats;"),
         ("Clam Chowder; Ham Sandwich; Bread Pudding;"),
         ("Tuna and Potato Patties; Boiled Cabbage and Carrots; Cupcakes;"),
         ("Chicken Caesar Salad; Mac N Cheese; Cookies;"),
         ("Baked Potato Soup; Turkey Sandwich; Fruit Salad;"),
         ("Shrimp Po' Boy Sandwich; Cajun Fries; Pralines;"),
         ("Mexican Street Corn Salad; Chicken Enchiladas; Churros;"),
         ("Caprese Stuffed Portobello Mushrooms; Garlic Bread; Tiramisu;"),
         ("Mediterranean Wrap; Tabbouleh Salad; Date Balls;"),
         ("Meatloaf; Macaroni and Cheese; Carrots; Peach Cobbler;"),
         ("Tuna melt Sandwich; Coleslaw; Fruit Salad;"),
         ("Sausage Pasta; Garlic Bread, Peas; Tapioca Pudding;"),
         ("Chicken Pot Pie; Carrot Souffle; Fruit Ambrosia;")]

dinner = [("Tuna Salad; Corn, Salad; Fruit;"),
          ("Chicken Quesadillas; Bean Salad; Pie;"),
          ("Chicken Egg Rolls; Fried Rice; Tapioca Pudding;"),
          ("Subway Sandwiches; Chips; Fruit Salad;"),
          ("Corn Dogs; Coleslaw; Ice-Cream;"),
          ("Chicken Salad; French Fries; Pudding;"),
          ("Clam Chowder; Ham Sandwiches; Pie;"),
          ("Chili; Grilled Cheese Sandwich; Fruit Salad;"),
          ("Tuna Patties; Creamed Corn; Cupcake;"),
          ("Soft Beef Tacos; Cilantro Rice; Ice-Cream;"),
          ("Albondigas Soup; Quesadilla; Pie;"),
          ("Boneless Wings; Potatoes; Fruit Salad;"),
          ("Honey Baked Chicken; Mashed Potatoes, Veggies; Cake;"),
          ("Chicken Teriyaki; Veggies, Rice; Berry Shortcake;"),
          ("Spaghetti and Meat Sauce; Garlic Bread; Caesar Salad; Ice-Cream;"),
          ("Grilled Lemon Herb Salmon; Quinoa Salad; Fruit Kabobs;"),
          ("Vegetable Stir-Fry; Steamed Brown Rice; Mango Sorbet;"),
          ("Lemon Garlic Shrimp Scampi; Roasted Asparagus; Lemon Gelato;"),
          ("Caprese Stuffed Chicken; Mixed Green Salad; Tiramisu;"),
          ("Vegetarian Sushi Roll; Edamame; Green Tea Ice Cream;"),
          ("Pesto Zucchini Noodles; Cherry Tomatoes; Almond Biscotti;"),
          ("Baked Stuffed Bell Peppers; Side Garden Salad; Fresh Berries;"),
          ("Honey Mustard Glazed Chicken; Grilled Vegetables; Angel Food Cake with Berries;"),
          ("Tofu and Broccoli Stir-Fry; Brown Rice; Mochi Ice Cream;"),
          ("Mediterranean Pasta Salad; Greek Yogurt with Honey; Date Balls;"),
          ("Zucchini and Tomato Frittata; Mixed Fruit Salad; Ricotta Lemon Cake;"),
          ("Cauliflower Rice Sushi Roll; Miso Soup; Sesame Cookies;"),
          ("Greek Quinoa Stuffed Peppers; Cucumber Salad; Baklava;"),
          ("Lemon Garlic Shrimp Zoodles; Garlic Breadsticks; Lemon Sorbet;"),
          ("Stuffed Portobello Mushrooms; Arugula Salad; Tiramisu;"),
          ("Lentil Soup; Cheese Toast; Brownie Bites;"),
          ("Salmon Salad; Pita Bread; Chocolate Pudding;"),
          ("Chicken Caesar Salad; Garlic Breadsticks; Gelato;"),
          ("Turkey Meatballs; Spaghetti Squash; Apple Slices w/ Caramel Dip;"),
          ("Pork Chops; Potatoes, Salad; Cake;")]